### ISSUE TITLE
Lutronic won't start

### ISSUE THREAD

**Issue by snoge** [gcortes/Lutronic#1]
Hi, done all as described but Lutronic.rb won't start. yaml file is in same directory

Air11s-Air:~ air11$ ruby /Users/air11/Scripts/Lutronic.rb
/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- active_support/all (LoadError)
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/air11/Scripts/Lutronic.rb:6:in `<main>'
Air11s-Air:~ air11$ 

Air11s-Air:~ air11$ ruby -version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
-e:1:in `<main>': undefined local variable or method `rsion' for main:Object (NameError)
Air11s-Air:~ air11$

**Comment by AdamGT3** [comment]
HI

I get the same issue.

Can anyone help?

Thanks

**Comment by snoge** [comment]
I have got ruby with all gems running but get these errors, what else is missing?

~/scripts $ sudo ruby Lutronic.rb
/usr/lib/ruby/vendor_ruby/net/telnet.rb:340:in `+': no implicit conversion of nil into String (TypeError)
	from /usr/lib/ruby/vendor_ruby/net/telnet.rb:340:in `initialize'
	from Lutronic.rb:32:in `new'
	from Lutronic.rb:32:in `telnetLogin'
	from Lutronic.rb:119:in `<main>'
